using System.Collections.Generic;

namespace DevTeam.Core.Models;

/// <summary>
/// Represents the planner's output for a single phase — the set of
/// tasks to be executed, their order, and the phase's overall goal.
/// Phase plans are generated by the Planner agent from user requirements
/// and saved as YAML files for the Global Project Orchestrator (GPO)
/// to consume.
/// </summary>
public class PhasePlan
{
    /// <summary>
    /// Unique identifier of the phase (e.g. "A", "B", "C").
    /// </summary>
    public string PhaseId { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable name of the phase (e.g. "Project Setup & Core Services").
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// High-level goal of the phase — what the system should be able
    /// to do once all tasks in this phase are complete.
    /// </summary>
    public string Goal { get; set; } = string.Empty;

    /// <summary>
    /// The ordered list of task specifications that make up this phase.
    /// </summary>
    public List<TaskSpec> Tasks { get; set; } = [];

    /// <summary>
    /// Estimated total effort for the entire phase in person-days.
    /// </summary>
    public double EstimatedEffortDays { get; set; }

    /// <summary>
    /// Gate criteria that must be met before the phase is considered
    /// complete (e.g. "Project compiles", "All tests pass").
    /// </summary>
    public List<string> PhaseGates { get; set; } = [];
}