using System.Collections.Generic;

namespace DevTeam.Core.Models;

/// <summary>
/// Represents the planner's output for a single phase — the set of
/// tasks to be executed and the phase's overall goal. Phase plans are
/// generated by the Planner agent from approved requirements, saved as
/// individual markdown files (e.g. <c>phases/PHASE-001.md</c>), and
/// consumed by the Global Project Orchestrator (GPO). The phase carries
/// its own runtime status so the system can be paused and resumed.
/// </summary>
public class PhasePlan
{
    /// <summary>
    /// Unique identifier of the phase (e.g. "A", "B", "C").
    /// </summary>
    public string PhaseId { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable name of the phase (e.g. "Project Setup & Core Services").
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// High-level goal of the phase — what the system should be able
    /// to do once all tasks in this phase are complete.
    /// </summary>
    public string Goal { get; set; } = string.Empty;

    /// <summary>
    /// The ordered list of task specifications that make up this phase.
    /// Each task carries its own runtime state.
    /// </summary>
    public List<TaskSpec> Tasks { get; set; } = [];

    /// <summary>
    /// Addenda created for this phase after User-requested changes.
    /// </summary>
    public List<Addendum> Addenda { get; set; } = [];

    /// <summary>
    /// Estimated total effort for the entire phase in person-days.
    /// </summary>
    public double EstimatedEffortDays { get; set; }

    /// <summary>
    /// Gate criteria that must be met before the phase is considered
    /// complete (e.g. "Project compiles", "All tests pass").
    /// </summary>
    public List<string> PhaseGates { get; set; } = [];

    // ── Runtime Status (persisted for resume capability) ──────────────

    /// <summary>
    /// Current lifecycle status of the phase.
    /// </summary>
    public PhaseStatus Status { get; set; } = PhaseStatus.NotStarted;

    /// <summary>
    /// PR number for the phase's pull request, if created.
    /// </summary>
    public int? PrNumber { get; set; }

    /// <summary>
    /// Status of the phase's PR (e.g. "pending", "merged", "closed").
    /// </summary>
    public string? PrStatus { get; set; }

    /// <summary>
    /// Relative file path to the phase plan document (e.g. "phases/PHASE-001.md").
    /// </summary>
    public string FilePath { get; set; } = string.Empty;
}